import { PrismaClient, Prisma } from '@prisma/client';

const prisma = new PrismaClient();

const lists = {
  UNHRC: [
    { alloc: "Islamic Republic of Afghanistan", other: "" },
    { alloc: "People's Democratic Republic of Algeria", other: "" },
    { alloc: "People's Republic of Albania", other: "" },
    { alloc: "Argentine Republic", other: "" },
    { alloc: "Republic of Austria", other: "" },
    { alloc: "Commonwealth of Australia", other: "" },
    { alloc: "Republic of Botswana", other: "" },
    { alloc: "Republic of Burundi", other: "" },
    { alloc: "Federative Republic of Brazil", other: "" },
    { alloc: "Commonwealth of the Bahamas", other: "" },
    { alloc: "People's Republic of Bangladesh", other: "" },
    { alloc: "Kingdom of Cambodia", other: "" },
    { alloc: "Republic of Cyprus", other: "" },
    { alloc: "Republic of China", other: "" },
    { alloc: "Republic of Cuba", other: "" },
    { alloc: "Central African Republic", other: "" },
    { alloc: "Canadian Confederation", other: "" },
    { alloc: "Czechoslovak Socialist Republic", other: "" },
    { alloc: "Kingdom of Denmark", other: "" },
    { alloc: "Commonwealth of Dominica", other: "" },
    { alloc: "Republic of Ecuador", other: "" },
    { alloc: "Arab Republic of Egypt", other: "" },
    { alloc: "Republic of Fiji", other: "" },
    { alloc: "Republic of Finland", other: "" },
    { alloc: "French Republic", other: "" },
    { alloc: "Federal Republic of Germany (West Germany)", other: "" },
    { alloc: "German Democratic Republic (East Germany)", other: "" },
    { alloc: "Republic of the Gambia", other: "" },
    { alloc: "Hellenic Republic (Greece)", other: "" },
    { alloc: "Republic of Guatemala", other: "" },
    { alloc: "Hungarian People's Republic", other: "" },
    { alloc: "Republic of Iceland", other: "" },
    { alloc: "Republic of India", other: "" },
    { alloc: "Republic of Iraq", other: "" },
    { alloc: "State of Israel", other: "" },
    { alloc: "Imperial State of Iran", other: "" },
    { alloc: "Japan", other: "" },
    { alloc: "Jamaica", other: "" },
    { alloc: "Republic of Kenya", other: "" },
    { alloc: "State of Kuwait", other: "" },
    { alloc: "Grand Duchy of Luxembourg", other: "" },
    { alloc: "Libyan Arab Republic", other: "" },
    { alloc: "Federation of Malaysia", other: "" },
    { alloc: "Republic of Malta", other: "" },
    { alloc: "Kingdom of Morocco", other: "" },
    { alloc: "Mongolian People's Republic", other: "" },
    { alloc: "Republic of Maldives", other: "" },
    { alloc: "Kingdom of Nepal", other: "" },
    { alloc: "Kingdom of the Netherlands", other: "" },
    { alloc: "New Zealand", other: "" },
    { alloc: "Kingdom of Norway", other: "" },
    { alloc: "Federal Republic of Nigeria", other: "" },
    { alloc: "Sultanate of Oman", other: "" },
    { alloc: "Islamic Republic of Pakistan", other: "" },
    { alloc: "Republic of Peru", other: "" },
    { alloc: "Republic of Poland", other: "" },
    { alloc: "Portugese Republic", other: "" },
    { alloc: "State of Qatar", other: "" },
    { alloc: "Romanian Socialist Republic", other: "" },
    { alloc: "Republic of Rwanda", other: "" },
    { alloc: "Kingdom of Saudi Arabia", other: "" },
    { alloc: "Republic of Senegal", other: "" },
    { alloc: "Republic of Singapore", other: "" },
    { alloc: "Kingdom of Spain", other: "" },
    { alloc: "Socialist Republic of Somalia", other: "" },
    { alloc: "Kingdom of Swaziland", other: "" },
    { alloc: "Kingdom of Sweden", other: "" },
    { alloc: "Syrian Arab Republic", other: "" },
    { alloc: "Republic of Turkey", other: "" },
    { alloc: "Turkish Republic of Northern Cyprus (Observer)", other: "" },
    { alloc: "Union of Soviet Socialist Republics", other: "" },
    { alloc: "United Arab Emirates", other: "" },
    { alloc: "United Kingdom of Great Britain & Northern Ireland", other: "" },
    { alloc: "United States of America", other: "" },
    { alloc: "Socialist Republic of Vietnam", other: "" }
  ],
  UNSC: [
    { alloc: "Russian Federation", other: "Permanent 5" },
    { alloc: "United States of America", other: "Permanent 5" },
    { alloc: "People's Republic of China", other: "Permanent 5" },
    { alloc: "Republic of France", other: "Permanent 5" },
    { alloc: "United Kingdom of Great Britain and Northern Ireland", other: "Permanent 5" },
    { alloc: "People’s Democratic Republic of Algeria", other: "Non Permanent Member" },
    { alloc: "Kingdom of Denmark", other: "Non Permanent Member" },
    { alloc: "Hellenic Republic (Greece)", other: "Non Permanent Member" },
    { alloc: "Co-operative Republic of Guyana", other: "Non Permanent Member" },
    { alloc: "Islamic Republic of Pakistan", other: "Non Permanent Member" },
    { alloc: "Republic of Panama", other: "Non Permanent Member" },
    { alloc: "Republic of Korea", other: "Non Permanent Member" },
    { alloc: "Republic of Sierra Leone", other: "Non Permanent Member" },
    { alloc: "Republic of Slovenia", other: "Non Permanent Member" },
    { alloc: "Federal Republic of Somalia", other: "Non Permanent Member" },
    { alloc: "Kingdom of Morocco", other: "Observer States" },
    { alloc: "Kingdom of Spain", other: "Observer States" },
    { alloc: "Islamic Republic of Mauritania", other: "Observer States" },
    { alloc: "Arab Republic of Egypt", other: "Observer States" },
    { alloc: "Republic of South Africa", other: "Observer States" },
    { alloc: "Federal Republic of Nigeria", other: "Observer States" },
    { alloc: "Islamic Republic of Iran", other: "Observer States" },
    { alloc: "State of Israel", other: "Observer States" },
    { alloc: "Kingdom of Saudi Arabia", other: "Observer States" },
    { alloc: "Republic of Türkiye", other: "Observer States" },
    { alloc: "Federal Democratic Republic of Ethiopia", other: "Observer States" }
  ],
  LS: [
    { alloc: "Narendra Modi", other: "Bharatiya Janta Party" },
    { alloc: "Amit Shah", other: "Bharatiya Janta Party" },
    { alloc: "Rajnath Singh", other: "Bharatiya Janta Party" },
    { alloc: "Nitin Gadkari", other: "Bharatiya Janta Party" },
    { alloc: "Smriti Irani", other: "Bharatiya Janta Party" },
    { alloc: "Anurag Thakur", other: "Bharatiya Janta Party" },
    { alloc: "Piyush Goyal", other: "Bharatiya Janta Party" },
    { alloc: "Jyotiraditya Scindia", other: "Bharatiya Janta Party" },
    { alloc: "Bhupender Yadav", other: "Bharatiya Janta Party" },
    { alloc: "Tejasvi Surya", other: "Bharatiya Janta Party" },
    { alloc: "Rahul Gandhi", other: "Indian National Congress" },
    { alloc: "Mallikarjun Kharge", other: "Indian National Congress" },
    { alloc: "Shashi Tharoor", other: "Indian National Congress" },
    { alloc: "Adhir Ranjan Chowdhury", other: "Indian National Congress" },
    { alloc: "Jairam Ramesh", other: "Indian National Congress" },
    { alloc: "Priyanka Gandhi Vadra", other: "Indian National Congress" },
    { alloc: "K. C. Venugopal", other: "Indian National Congress" },
    { alloc: "Akhilesh Yadav", other: "Samajwadi Party" },
    { alloc: "Dimple Yadav", other: "Samajwadi Party" },
    { alloc: "Jayant Chaudhary", other: "Rashtriya Lok Dal" },
    { alloc: "Sharad Pawar", other: "NCP (Sharad Faction)" },
    { alloc: "Praful Patel", other: "NCP (Ajit Faction)" },
    { alloc: "Supriya Sule", other: "NCP – Sharad Faction" },
    { alloc: "Uddhav Thackeray", other: "Shiv Sena (UBT)" },
    { alloc: "Eknath Shinde", other: "Shiv Sena (Shinde)" },
    { alloc: "Arvind Kejriwal", other: "Aam Aadmi Party " },
    { alloc: "Bhagwant Mann", other: "Aam Aadmi Party " },
    { alloc: "Raghav Chadha", other: "Aam Aadmi Party " },
    { alloc: "Asaduddin Owaisi", other: "AIMIM" },
    { alloc: "K. Chandrashekar Rao", other: "Bharat Rashtra Samithi " },
    { alloc: "Kalvakuntla Kavitha", other: "Bharat Rashtra Samithi " },
    { alloc: "M. K. Stalin", other: "DMK" },
    { alloc: "Kanimozhi Karunanidhi", other: "DMK" },
    { alloc: "Edappadi K. Palaniswami", other: "AIADMK" },
    { alloc: "H. D. Kumaraswamy", other: "JD(S)" },
    { alloc: "Deve Gowda", other: "JD(S)" },
    { alloc: "Hemant Soren", other: "Jharkhand Mukti Morcha " },
    { alloc: "Mamata Banerjee", other: "TMC" },
    { alloc: "Abhishek Banerjee", other: "TMC" },
    { alloc: "Sitaram Yechury", other: "CPI(M)" },
    { alloc: "D. Raja", other: "CPI" },
    { alloc: "Badruddin Ajmal", other: "AIUDF" },
    { alloc: "Chirag Paswan", other: "Lok Janshakti Party" },
    { alloc: "Pawan Kalyan", other: "Jana Sena Party" },
    { alloc: "Y. S. Jagan Mohan Reddy", other: "YSRCP" },
    { alloc: "Naveen Patnaik", other: "Biju Janata Dal" },
    { alloc: "Nitish Kumar", other: "JD(U)" },
    { alloc: "Sanjay Raut", other: "Shiv Sena (UBT)" },
    { alloc: "Mehbooba Mufti", other: "J&K PDP" },
    { alloc: "Farooq Abdullah", other: "J&K National Conference" },
    { alloc: "Kiren Rijiju", other: "BJP" },
    { alloc: "N. Biren Singh", other: "BJP" },
    { alloc: "Navneet Rana", other: "Independent MP (Amravati)" },
    { alloc: "Nishikant Dubey", other: "Bharatiya Janata Party" },
    { alloc: "Justice (Retd.) Ranjan Gogoi", other: "Nominated Member" },
  ],
  IPC: [
    { alloc: "Times of India", other: "" },
    { alloc: "New York Times", other: "" },
    { alloc: "BBC", other: "" },
    { alloc: "CNN", other: "" },
    { alloc: "Reuters", other: "" },
    { alloc: "Al Jazeera", other: "" },
    { alloc: "NDTV", other: "" },
    { alloc: "The Gaurdian", other: "" },
    { alloc: "Xinhua News Agency", other: "" },
    { alloc: "The Daily Telegraph", other: "" },
    { alloc: "South China Morning Post", other: "" },
    { alloc: "TASS", other: "" },
    { alloc: "Brut", other: "" },
    { alloc: "NowThis", other: "" },
    { alloc: "ATTN", other: "" },
    { alloc: "The Tatva", other: "" },
    { alloc: "MeidasTouch", other: "" },
    { alloc: "Double Down News ", other: "" },
    { alloc: "TLDR news", other: "" },
    { alloc: "Impact", other: "" },
    { alloc: "Vox", other: "" },
    { alloc: "Pubity", other: "" },
    { alloc: "Press Trust of India", other: "" },
    { alloc: "African News Agency", other: "" },
    { alloc: "Agence France-Presse", other: "" },
    { alloc: "Doordarshan", other: "" },
    { alloc: "Kyodo News", other: "" },
    { alloc: "Islamic Republic News Agency", other: "" },
    { alloc: "Kuwait times", other: "" },
    { alloc: "Tehran times", other: "" },
  ],
  UNODC: [
    { alloc: "Myanmar", other: "" },
    { alloc: "Thailand", other: "" },
    { alloc: "Laos", other: "" },
    { alloc: "Veitnam", other: "" },
    { alloc: "Cambodia", other: "" },
    { alloc: "Malaysia", other: "" },
    { alloc: "Indonesia", other: "" },
    { alloc: "Phillipines", other: "" },
    { alloc: "Singapore", other: "" },
    { alloc: "Brunei", other: "" },
    { alloc: "Timor-Leste", other: "" },
    { alloc: "United States", other: "" },
    { alloc: "China ", other: "" },
    { alloc: "France", other: "" },
    { alloc: "United Kingdom", other: "" },
    { alloc: "Russia", other: "" },
    { alloc: "India", other: "" },
    { alloc: "Bangladesh", other: "" },
    { alloc: "Pakistan", other: "" },
    { alloc: "Australia", other: "" },
    { alloc: "Japan", other: "" },
    { alloc: "South Korea", other: "" },
    { alloc: "North Korea", other: "" },
    { alloc: "Germany", other: "" },
    { alloc: "Netherlands", other: "" },
    { alloc: "New Zealand", other: "" },
    { alloc: "Canada", other: "" },
    { alloc: "Italy ", other: "" },
    { alloc: "Norway", other: "" },
    { alloc: "Sweden", other: "" },
    { alloc: "Switzerland", other: "" },
    { alloc: "Spain ", other: "" },
    { alloc: "Iran", other: "" },
    { alloc: "Kazakhastan", other: "" },
    { alloc: "UAE", other: "" },
    { alloc: "Mexico", other: "" },
    { alloc: "Colombia", other: "" },
    { alloc: "Afghanisthan", other: "" },
    { alloc: "Venezuela", other: "" },
    { alloc: "Nigeria", other: "" },
    { alloc: "Brazil", other: "" },
    { alloc: "Guinea Bisseau", other: "" },
    { alloc: "Peru", other: "" },
    { alloc: "Turkey", other: "" },
    { alloc: "Sri Lanka", other: "" },
    { alloc: "Maldives", other: "" },
    { alloc: "Bhutan", other: "" },
    { alloc: "Nepal", other: "" },
    { alloc: "Papua New Guinea", other: "" },
    { alloc: "Ecuador", other: "" },
    { alloc: "Panama", other: "" },
    { alloc: "Albania", other: "" },
    { alloc: "Serbia", other: "" },
    { alloc: "Kenya", other: "" },
    { alloc: "Tanzania", other: "" },
    { alloc: "Mozambique", other: "" },
    { alloc: "Morocco", other: "" },
    { alloc: "Ukraine", other: "" },
    { alloc: "Greece", other: "" },
    { alloc: "Slovenia", other: "" },
  ],
  CCC: [
    { alloc: 'Narendra Modi', other: 'Indian Prime Minister' },
    { alloc: 'Rajnath Singh', other: 'Indian Defence Minister' },
    { alloc: 'Amit Shah', other: 'Indian Home Minister' },
    { alloc: 'S. Jaishankar', other: 'Indian External Affairs Minister' },
    { alloc: 'Omar Abdullah', other: 'Indian Chief Minister of J&K' },
    { alloc: 'Ajit Doval', other: 'Indian National Security Advisor' },
    { alloc: 'General Anil Chauhan', other: 'Indian Chief of Defence Staff' },
    { alloc: 'General Upendra Dwivedi', other: 'Indian Chief of Army Staff' },
    { alloc: 'Admiral Dinesh Kumar Tripathi', other: 'Indian Chief of Naval Staff' },
    { alloc: 'Air Chief Marshal Amar Preet Singh', other: 'Indian Chief of Air Staff' },
    { alloc: 'Tapan Kumar Deka', other: 'Indian IB Chief' },
    { alloc: 'Lt. Gen. R.S. Raman', other: 'Indian Director General Military Intelligence' },
    { alloc: 'Lt. Gen. Dwivedi', other: 'Indian "GOC-in-C, Northern Command"' },
    { alloc: 'Lt. Gen. Rakesh Kapoor', other: 'Indian Western Command' },
    { alloc: 'Lt. Gen. H.S. Sahi', other: 'Indian XV Corps Commander (Kashmir)' },
    { alloc: 'Lt. Gen. Navin Sachdeva', other: 'Indian XVI Corps Commander (Jammu)' },
    { alloc: 'Shehbaz Sharif', other: 'Pakistani Prime Minister' },
    { alloc: 'Khawaja Asif', other: 'Pakistani Defence Minister' },
    { alloc: 'Rana Sanaullah', other: 'Pakistani Interior Minister' },
    { alloc: 'Ishaq Dar', other: 'Pakistani Foreign Minister' },
    { alloc: 'General Asim Munir', other: 'Pakistani Chief of Army Staff' },
    { alloc: 'Vice Admiral Naveed Ashraf', other: 'Pakistani Chief of Naval Staff' },
    { alloc: 'Air Chief Marshal Zaheer Ahmed Babar Sidhu', other: 'Pakistani Chief of Air Staff' },
    { alloc: 'General Sahir Shamshad Mirza', other: 'Pakistani Chairman Joint Chiefs of Staff Committee' },
    { alloc: 'Lt. Gen. Muhammad Asim Malik', other: 'Pakistani "Director General, ISI; National Security Advisor"' },
    { alloc: 'Lt. Gen. Syed Aamer Raza', other: 'Pakistani Chief of General Staff' },
    { alloc: 'Lt. Gen. Ayman Bilal Safdar', other: 'Pakistani "Commander X Corps, Rawalpindi"' },
    { alloc: 'Lt. Gen. Nauman Zakaria', other: 'Pakistani "Commander IV Corps, Lahore"' },
    { alloc: 'Lt. Gen. Muhammad Waseem Ashraf', other: 'Pakistani Military Intelligence Chief' },
    { alloc: 'Anwaar-ul-Haq Kakar', other: 'Pakistani National Security Advisor' },
    { alloc: 'Fuad Asadullah Khan', other: 'Pakistani Director General of IB' },
  ]
}

const seedData: Prisma.AllocationCreateInput[] = Object.entries(lists)
  .filter(([committee, _]) => committee === 'CCC')
  .flatMap(([committee, countries]) =>
    countries.map((country) => ({ ...country, committee: committee } as Prisma.AllocationCreateInput))
  );

console.log(seedData);

export async function main() {
  for (const data of seedData) {
    await prisma.allocation.create({ data });
  }
}

main();
